version: "3.1"

services:
  ghost:
    image: ghost:latest
    restart: always
    ports:
      - 8080:2368
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: pnWHPCnYghcXjj8rnUhUUnwH
      database__connection__database: ghost

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pnWHPCnYghcXjj8rnUhUUnwH
    volumes:
      - ./mysql:/var/lib/mysql
